-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
--CREATE PROCEDURE [dbo].[ApplicationLogInsert] 
--	 @AllicationName varchar(100)
--	,@Class varchar(255)
--	,@Method varchar(255)
--	,@Type varchar(255)
--	,@Text varchar(1000)
--	,@CreateUserId uniqueidentifier
--	,@CreateDateTime Datetime
--AS
--BEGIN
--	SET NOCOUNT ON;

--	EXECUTE [ApplicationUser].[dbo].[ApplicationLogInsert] 
--	   @AllicationName = @AllicationName
--	  ,@Class = @Class
--	  ,@Method = @Method
--	  ,@Type = @Type
--	  ,@Text = @Text
--	  ,@CreateUserId = @CreateUserId
--	  ,@CreateDateTime = @CreateDateTime
						
--END
