//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DentalCard
    {
        public int DentalCardId { get; set; }
        public int PatientId { get; set; }
        public byte OrderNumber { get; set; }
        public string Description { get; set; }
        public bool IsCheck { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
