//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientVisit()
        {
            this.PatientVisitPayments = new HashSet<PatientVisitPayment>();
            this.ScheduleRecords = new HashSet<ScheduleRecord>();
        }
    
        public int PatientVisitId { get; set; }
        public int PatientId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public System.TimeSpan VisitStartTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string PurposeOfVisit { get; set; }
        public string SubjectiveComplaints { get; set; }
        public string AdditionalResearch { get; set; }
        public string LaboratoryResearch { get; set; }
        public string ClinicalDiagnosis { get; set; }
        public string Treatment { get; set; }
        public string DoctorAssignments { get; set; }
        public Nullable<int> NextVizitRecordId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientVisitPayment> PatientVisitPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleRecord> ScheduleRecords { get; set; }
    }
}
