//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleRecord
    {
        public int ScheduleRecordId { get; set; }
        public int ScheduleRecordTypeId { get; set; }
        public int UserId { get; set; }
        public bool isFinished { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> PatientVisitId { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<System.TimeSpan> RecordStartTime { get; set; }
        public byte Duration { get; set; }
        public Nullable<decimal> CostOfFeautureServices { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PatientVisit PatientVisit { get; set; }
        public virtual ScheduleRecordType ScheduleRecordType { get; set; }
    }
}
