//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionData
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public System.DateTime SessionStart { get; set; }
        public Nullable<System.DateTime> SessionEnd { get; set; }
        public Nullable<int> AspUserId { get; set; }
        public string IPAddress { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
