//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserInfoId { get; set; }
        public int AspNetUserId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public Nullable<System.TimeSpan> WorkTimeFrom { get; set; }
        public Nullable<System.TimeSpan> WorkTimeTo { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
        public System.DateTime LastActivityDateUtc { get; set; }
        public bool IsLocked { get; set; }
        public bool IsDeleted { get; set; }
        public int TimeZoneId { get; set; }
        public int LanguageId { get; set; }
        public string Notepad { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Language Language { get; set; }
        public virtual TimeZone TimeZone { get; set; }
    }
}
