//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorPremium.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPublicPage
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string AboutOfDoctor { get; set; }
        public string DoctorService { get; set; }
        public string PublicEmailAddress { get; set; }
        public string PublicAddressForPatients { get; set; }
        public string PublicPhone { get; set; }
        public bool IsPublic { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public Nullable<System.DateTime> UpdateDateUtc { get; set; }
        public bool IsDeleted { get; set; }
        public int VisitCounter { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
