//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorPremium.Web.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я согласен.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите правильные символы с картинки и выключите CapsLock.
        /// </summary>
        public static string CapsButton {
            get {
                return ResourceManager.GetString("CapsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите лицензию..
        /// </summary>
        public static string CheckLicense {
            get {
                return ResourceManager.GetString("CheckLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string ConfirmBtn {
            get {
                return ResourceManager.GetString("ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения.
        /// </summary>
        public static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта подтверждена!.
        /// </summary>
        public static string ConfirmEmailPage {
            get {
                return ResourceManager.GetString("ConfirmEmailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша почта подтверждена. Пожалуйста войдите под вашим логином и паролем на сайт..
        /// </summary>
        public static string ConfirmEmailSucceccMsg {
            get {
                return ResourceManager.GetString("ConfirmEmailSucceccMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка..
        /// </summary>
        public static string ConfirmLink {
            get {
                return ResourceManager.GetString("ConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница подтверждения почты вручную.
        /// </summary>
        public static string ConfirmManualTitle {
            get {
                return ResourceManager.GetString("ConfirmManualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Вашу почту отправлено письмо для подтверждения регистрации. Если вам не пришло письмо о подтверждении регистрации попробуйте зарегистрироваться на другой email и напишите пожалуйста нам на почту о этой проблеме..
        /// </summary>
        public static string ConfirSendTitle {
            get {
                return ResourceManager.GetString("ConfirSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставьте код подтверждения.
        /// </summary>
        public static string EnterConfirmCode {
            get {
                return ResourceManager.GetString("EnterConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомнить пароль.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомнить.
        /// </summary>
        public static string ForgotPasswordBtn {
            get {
                return ResourceManager.GetString("ForgotPasswordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте свою почту и следуйте инструкции чтобы сбросить пароль..
        /// </summary>
        public static string ForgotPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос выполнен..
        /// </summary>
        public static string ForgotPasswordConfirmScs {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmScs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомнить пароль.
        /// </summary>
        public static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я согласен.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница входа.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должен быть не меньше {2} символов..
        /// </summary>
        public static string MustBeLeast {
            get {
                return ResourceManager.GetString("MustBeLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница регистрации.
        /// </summary>
        public static string RegisterPage {
            get {
                return ResourceManager.GetString("RegisterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor-premium сброс пароля..
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите заново свой новый пароль, нажав здесь:.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить пароль.
        /// </summary>
        public static string ResetPasswordBtn {
            get {
                return ResourceManager.GetString("ResetPasswordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был сброшен. Пожалуйста залогиньтесь для входа на сайт..
        /// </summary>
        public static string ResetPasswordConfirmMsg {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля выполнен..
        /// </summary>
        public static string ResetPasswordConfirmScs {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmScs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница сброса пароля.
        /// </summary>
        public static string ResetPasswordPage {
            get {
                return ResourceManager.GetString("ResetPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия..
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия использования Страниц Doctor-Premium.com
        ///Следующие условия применяются ко всем Страницам Doctor-Premium. Кроме того, все материалы ваших страниц должны соответствовать нормам законодательства вашей страны. Вы несете ответственность за обеспечение соответствия своей страницы всем применимым законам, стандартам и правилам законодательства вашей страны.
        ///Общие положения
        ///Запрещается использовать вашу страницу, если это противоречит законодательству вашей страны.
        ///Функции Страниц 
        ///Информация на страни [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TextLicense {
            get {
                return ResourceManager.GetString("TextLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию!.
        /// </summary>
        public static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor-premium подтверждение регистрации..
        /// </summary>
        public static string TopicConfirm {
            get {
                return ResourceManager.GetString("TopicConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите свою регистрацию, нажав на эту ссылку:.
        /// </summary>
        public static string TopicConfirmBody {
            get {
                return ResourceManager.GetString("TopicConfirmBody", resourceCulture);
            }
        }
    }
}
