//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientVisitLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientVisitLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorPremium.Web.Resources.PatientVisitLang", typeof(PatientVisitLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные исследования.
        /// </summary>
        public static string AdditionalSymptoms {
            get {
                return ResourceManager.GetString("AdditionalSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клинический диагноз.
        /// </summary>
        public static string ClinicalDiagnosis {
            get {
                return ResourceManager.GetString("ClinicalDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень планируемых услуг.
        /// </summary>
        public static string CommentNextVisit {
            get {
                return ResourceManager.GetString("CommentNextVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость, пример: 11,25.
        /// </summary>
        public static string CostOfFeautureServices {
            get {
                return ResourceManager.GetString("CostOfFeautureServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость оказанных услуг, пример: 100,55.
        /// </summary>
        public static string CostOfServices {
            get {
                return ResourceManager.GetString("CostOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата сегодняшнего визита.
        /// </summary>
        public static string DataVisits {
            get {
                return ResourceManager.GetString("DataVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату визита.
        /// </summary>
        public static string DataVisitsRequiered {
            get {
                return ResourceManager.GetString("DataVisitsRequiered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные рентгеновских обследований, лабораторных исследований..
        /// </summary>
        public static string DataX {
            get {
                return ResourceManager.GetString("DataX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление(Осторожно!).
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначения врача.
        /// </summary>
        public static string DoctorAppointments {
            get {
                return ResourceManager.GetString("DoctorAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель визита.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная цена.
        /// </summary>
        public static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визит пациента:.
        /// </summary>
        public static string LabelVisit {
            get {
                return ResourceManager.GetString("LabelVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата следующего визита.
        /// </summary>
        public static string NextVisitDate {
            get {
                return ResourceManager.GetString("NextVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время визита.
        /// </summary>
        public static string NextVisitStartTime {
            get {
                return ResourceManager.GetString("NextVisitStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уплачено, пример: 10,23.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Субъективные жалобы.
        /// </summary>
        public static string Symptoms {
            get {
                return ResourceManager.GetString("Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время визита.
        /// </summary>
        public static string TimeOfVisit {
            get {
                return ResourceManager.GetString("TimeOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите время.
        /// </summary>
        public static string TimeOfVisitReqired {
            get {
                return ResourceManager.GetString("TimeOfVisitReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведенное лечение.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
    }
}
