//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublicS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublicS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorPremium.Web.Resources.PublicS", typeof(PublicS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О  нас.
        /// </summary>
        public static string AboutDoctor {
            get {
                return ResourceManager.GetString("AboutDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        public static string abouts {
            get {
                return ResourceManager.GetString("abouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться с друзьями сайтом..
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт закрыт, это режим предварительного просмотра..
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактная информация.
        /// </summary>
        public static string ContactI {
            get {
                return ResourceManager.GetString("ContactI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги и цены:.
        /// </summary>
        public static string DoctorService {
            get {
                return ResourceManager.GetString("DoctorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание, ваш сайт  сейчас  выключен, вам необходимо после того как все поля заполните включить сайт кнопкой: ВКЛ / ВЫКЛ.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEB SITE:.
        /// </summary>
        public static string labelHeader {
            get {
                return ResourceManager.GetString("labelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О. .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес приема:.
        /// </summary>
        public static string PublicAddressForPatients {
            get {
                return ResourceManager.GetString("PublicAddressForPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел. для записи:.
        /// </summary>
        public static string PublicPhone {
            get {
                return ResourceManager.GetString("PublicPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить адрес сайта..
        /// </summary>
        public static string Seo {
            get {
                return ResourceManager.GetString("Seo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string SERVICES {
            get {
                return ResourceManager.GetString("SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать друзьям программу.
        /// </summary>
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой личный сайт..
        /// </summary>
        public static string SharedMas {
            get {
                return ResourceManager.GetString("SharedMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш сайт был заблокирован администраторами..
        /// </summary>
        public static string SiteIsDeteted {
            get {
                return ResourceManager.GetString("SiteIsDeteted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональная страница не создана или закрыта, необходимо в странице настройках сайта его включить..
        /// </summary>
        public static string SiteNoFoundText {
            get {
                return ResourceManager.GetString("SiteNoFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес сайта в интернете:.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инофрмация для сайта.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
