//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorPremium.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пациенты.
        /// </summary>
        public static string BasePatients {
            get {
                return ResourceManager.GetString("BasePatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить себе..
        /// </summary>
        public static string BuyPersonalVariant {
            get {
                return ResourceManager.GetString("BuyPersonalVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы  точно хотите удалить?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сloud-based healthcare platform.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpButtonUrl {
            get {
                return ResourceManager.GetString("HelpButtonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример как заполнять эту страницу.
        /// </summary>
        public static string InfoAllBlueButton {
            get {
                return ResourceManager.GetString("InfoAllBlueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь?.
        /// </summary>
        public static string InfoAllButtonHelp {
            get {
                return ResourceManager.GetString("InfoAllButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео инструкция.
        /// </summary>
        public static string InfoAllButtonVidioHelp {
            get {
                return ResourceManager.GetString("InfoAllButtonVidioHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример как заполнять рассписание.
        /// </summary>
        public static string InfoSchedule {
            get {
                return ResourceManager.GetString("InfoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введённые данные будут потеряны!.
        /// </summary>
        public static string Infowillbelost {
            get {
                return ResourceManager.GetString("Infowillbelost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to база пациентов,	база данных пациентов, база врач пациент, база пациентов больниц, 
        ///медицинская база данных пациентов, база пациентов программа, база данных пациентов больниц,
        ///база пациентов поликлиники, база пациентов стоматологии, база ведения пациентов,
        ///список пациентов больницы база данных, база данных пациентов поликлиники, база неизвестных пациентов
        ///база данных пациентов исследования, база учета пациентов, картотека пациентов.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой сайт.
        /// </summary>
        public static string MySite {
            get {
                return ResourceManager.GetString("MySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигация.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пациент.
        /// </summary>
        public static string NewCard {
            get {
                return ResourceManager.GetString("NewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 90 дн..
        /// </summary>
        public static string NinetyBefore {
            get {
                return ResourceManager.GetString("NinetyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 90 дн..
        /// </summary>
        public static string NinetyNext {
            get {
                return ResourceManager.GetString("NinetyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокнот.
        /// </summary>
        public static string Notepad {
            get {
                return ResourceManager.GetString("Notepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 180 дн..
        /// </summary>
        public static string OneEightyBefore {
            get {
                return ResourceManager.GetString("OneEightyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 180 дн..
        /// </summary>
        public static string OneEightyNext {
            get {
                return ResourceManager.GetString("OneEightyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 120 дн..
        /// </summary>
        public static string OneTwentyBefore {
            get {
                return ResourceManager.GetString("OneTwentyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 120 дн..
        /// </summary>
        public static string OneTwentynext {
            get {
                return ResourceManager.GetString("OneTwentynext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на сайт.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка страницы .
        /// </summary>
        public static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 7 дн..
        /// </summary>
        public static string SevenBefore {
            get {
                return ResourceManager.GetString("SevenBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 7 дн..
        /// </summary>
        public static string SevenNext {
            get {
                return ResourceManager.GetString("SevenNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 60 дн..
        /// </summary>
        public static string SixtyBefore {
            get {
                return ResourceManager.GetString("SixtyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 60 дн..
        /// </summary>
        public static string SixtyNext {
            get {
                return ResourceManager.GetString("SixtyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 30 дн..
        /// </summary>
        public static string ThirtyBefore {
            get {
                return ResourceManager.GetString("ThirtyBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 30 дн..
        /// </summary>
        public static string ThirtyNext {
            get {
                return ResourceManager.GetString("ThirtyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Healthcare Platform..
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to получено / ожидается.
        /// </summary>
        public static string TitleMoney {
            get {
                return ResourceManager.GetString("TitleMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 1 дн..
        /// </summary>
        public static string TodayBefore {
            get {
                return ResourceManager.GetString("TodayBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 1 дн..
        /// </summary>
        public static string TodayNext {
            get {
                return ResourceManager.GetString("TodayNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовый аккаунт. Внимание!.
        /// </summary>
        public static string Varning {
            get {
                return ResourceManager.GetString("Varning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вводите только тестовые данные. Вы находитесь в тестовом аккаунте. Для ввода своих личных данных по пациентам, пройдите  бесплатную быструю регистрацию..
        /// </summary>
        public static string VarningText {
            get {
                return ResourceManager.GetString("VarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string VarningTextLink {
            get {
                return ResourceManager.GetString("VarningTextLink", resourceCulture);
            }
        }
    }
}
