//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Schedule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schedule() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorPremium.Web.Resources.Schedule", typeof(Schedule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена должна быть заполнена.
        /// </summary>
        public static string CostOff {
            get {
                return ResourceManager.GetString("CostOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительная цена.
        /// </summary>
        public static string CostOfFeautureServices {
            get {
                return ResourceManager.GetString("CostOfFeautureServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать визит.
        /// </summary>
        public static string CreateHistory {
            get {
                return ResourceManager.GetString("CreateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать карточку пациента.
        /// </summary>
        public static string CreatePatient {
            get {
                return ResourceManager.GetString("CreatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание задачи.
        /// </summary>
        public static string DescriptionTask {
            get {
                return ResourceManager.GetString("DescriptionTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в визит.
        /// </summary>
        public static string GoToHistory {
            get {
                return ResourceManager.GetString("GoToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в карточку пациента.
        /// </summary>
        public static string GoToPatient {
            get {
                return ResourceManager.GetString("GoToPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация .
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о визите.
        /// </summary>
        public static string InfoLastApp {
            get {
                return ResourceManager.GetString("InfoLastApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о задаче.
        /// </summary>
        public static string InfoLastTask {
            get {
                return ResourceManager.GetString("InfoLastTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия, имя, отчество, тел:.
        /// </summary>
        public static string NamePatient {
            get {
                return ResourceManager.GetString("NamePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема задачи.
        /// </summary>
        public static string NameTask {
            get {
                return ResourceManager.GetString("NameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пациент.
        /// </summary>
        public static string NewApp {
            get {
                return ResourceManager.GetString("NewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в расписание.
        /// </summary>
        public static string NewAppoint {
            get {
                return ResourceManager.GetString("NewAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string NewModalTask {
            get {
                return ResourceManager.GetString("NewModalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый визит.
        /// </summary>
        public static string NewModalVisit {
            get {
                return ResourceManager.GetString("NewModalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая задача.
        /// </summary>
        public static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый визит.
        /// </summary>
        public static string NewVisit {
            get {
                return ResourceManager.GetString("NewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату.
        /// </summary>
        public static string RecordDateRequired {
            get {
                return ResourceManager.GetString("RecordDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        public static string RecordStartTime {
            get {
                return ResourceManager.GetString("RecordStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите время начала.
        /// </summary>
        public static string RecordStartTimeRequired {
            get {
                return ResourceManager.GetString("RecordStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пациента.
        /// </summary>
        public static string SearchPatient {
            get {
                return ResourceManager.GetString("SearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Существующий пациент.
        /// </summary>
        public static string SecondApp {
            get {
                return ResourceManager.GetString("SecondApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже существующие пациенты.
        /// </summary>
        public static string SecondVisit {
            get {
                return ResourceManager.GetString("SecondVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перечень планируемых услуг.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to задачи.
        /// </summary>
        public static string TaskLabel {
            get {
                return ResourceManager.GetString("TaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время .
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О., Тел..
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполните поле..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to визита.
        /// </summary>
        public static string VizitLabel {
            get {
                return ResourceManager.GetString("VizitLabel", resourceCulture);
            }
        }
    }
}
