/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Dateline Standard Time',-720,'(UTC-12:00) Линия перемены дат','(GMT-12:00) Dateline Standard Time',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('UTC-11',-660,'(UTC-11:00) Время в формате UTC -11','(GMT-11:00) UTC time',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Hawaiian Standard Time',-600,'(UTC-10:00) Гавайи','(GMT-10:00) Hawaii',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Alaskan Standard Time',-540,'(UTC-09:00) Аляска','(GMT-09:00) Alaska',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Pacific Standard Time (Mexico)',-480,'(UTC-08:00) Нижняя Калифорния','(GMT-08:00) Tijuana, Baja California',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Pacific Standard Time',-480,'(UTC-08:00) Тихоокеанское время (США и Канада)','(GMT-08:00) Pacific Time (US & Canada)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('US Mountain Standard Time',-420,'(UTC-07:00) Аризона','(GMT-07:00) Arizona',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Mountain Standard Time',-420,'(UTC-07:00) Горное время (США и Канада)','(GMT-07:00) Mountain Time (US & Canada)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Mountain Standard Time (Mexico)',-420,'(UTC-07:00) Ла-Пас, Мазатлан, Чихуахуа','(GMT-07:00) Chihuahua, La Paz, Mazatlan',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Standard Time (Mexico)',-360,'(UTC-06:00) Гвадалахара, Мехико, Монтеррей','(GMT-06:00) Guadalajara, Mexico City, Monterrey',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Canada Central Standard Time',-360,'(UTC-06:00) Саскачеван','(GMT-06:00) Saskatchewan',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central America Standard Time',-360,'(UTC-06:00) Центральная Америка','(GMT-06:00) Central America',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Standard Time',-360,'(UTC-06:00) Центральное время (США и Канада)','(GMT-06:00) Central Time (US & Canada)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('SA Pacific Standard Time',-300,'(UTC-05:00) Богота, Кито, Лима, Рио-Бранко','(GMT-05:00) Bogota, Lima, Quito, Rio Branco',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Eastern Standard Time',-300,'(UTC-05:00) Восточное время (США и Канада)','(GMT-05:00) Eastern Time (US & Canada)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('US Eastern Standard Time',-300,'(UTC-05:00) Индиана (восток)','(GMT-05:00) Indiana (East)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Venezuela Standard Time',-270,'(UTC-04:30) Каракас','(GMT-04:30) Caracas',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Paraguay Standard Time',-240,'(UTC-04:00) Асунсьон','(GMT-04:00) Asunsion',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Atlantic Standard Time',-240,'(UTC-04:00) Атлантическое время (Канада)','(GMT-04:00) Atlantic Time (Canada)',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('SA Western Standard Time',-240,'(UTC-04:00) Джорджтаун, Ла-Пас, Манаус, Сан-Хуан','(GMT-04:00) La Paz',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Brazilian Standard Time',-240,'(UTC-04:00) Куяба','(GMT-04:00) Manaus',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Pacific SA Standard Time',-240,'(UTC-04:00) Сантьяго','(GMT-04:00) Santiago',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Newfoundland Standard Time',-210,'(UTC-03:30) Ньюфаундленд','(GMT-03:30) Newfoundland',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('E. South America Standard Time',-180,'(UTC-03:00) Бразилия','(GMT-03:00) Brasilia',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Argentina Standard Time',-180,'(UTC-03:00) Буэнос-Айрес','(GMT-03:00) Buenos Aires',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Greenland Standard Time',-180,'(UTC-03:00) Гренландия','(GMT-03:00) Greenland',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('SA Eastern Standard Time',-180,'(UTC-03:00) Кайенна, Форталеза','(GMT-03:00) Georgetown',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Montevideo Standard Time',-180,'(UTC-03:00) Монтевидео','(GMT-03:00) Montevideo',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Bahia Standard Time',-180,'(UTC-03:00) Сальвадор','(GMT-03:00) Salvador',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('UTC-02',-120,'(UTC-02:00) Время в формате UTC -02','(GMT-02:00) UTC time',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Mid-Atlantic Standard Time',-120,'(UTC-02:00) Среднеатлантическое время - старое','(GMT-02:00) Mid-Atlantic',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Azores Standard Time',-60,'(UTC-01:00) Азорские о-ва','(GMT-01:00) Azores',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Cape Verde Standard Time',-60,'(UTC-01:00) О-ва Зеленого Мыса','(GMT-01:00) Cape Verde Is.',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('UTC',0,'(UTC) Время в формате UTC','(GMT) UTC time',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('GMT Standard Time',0,'(UTC) Дублин, Лиссабон, Лондон, Эдинбург','(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Morocco Standard Time',0,'(UTC) Касабланка','(GMT) Casablanca',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Greenwich Standard Time',0,'(UTC) Монровия, Рейкьявик','(GMT) Monrovia, Reykjavik',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('W. Europe Standard Time',60,'(UTC+01:00) Амстердам, Берлин, Берн, Вена, Рим, Стокгольм','(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Europe Standard Time',60,'(UTC+01:00) Белград, Братислава, Будапешт, Любляна, Прага','(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Romance Standard Time',60,'(UTC+01:00) Брюссель, Копенгаген, Мадрид, Париж','(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central European Standard Time',60,'(UTC+01:00) Варшава, Загреб, Сараево, Скопье','(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Namibia Standard Time',60,'(UTC+01:00) Виндхук','(GMT+01:00) Windhoek',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('W. Central Africa Standard Time',60,'(UTC+01:00) Западная Центральная Африка','(GMT+01:00) West Central Africa',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Jordan Standard Time',120,'(UTC+02:00) Амман','(GMT+02:00) Amman',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('GTB Standard Time',120,'(UTC+02:00) Афины, Бухарест','(GMT+02:00) Athens, Bucharest, Istanbul',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Middle East Standard Time',120,'(UTC+02:00) Бейрут','(GMT+02:00) Beirut',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('FLE Standard Time',120,'(UTC+02:00) Вильнюс, Киев, Рига, София, Таллин, Хельсинки','(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('E. Europe Standard Time',120,'(UTC+02:00) Восточная Европа','(GMT+02:00) Minsk',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Syria Standard Time',120,'(UTC+02:00) Дамаск','(GMT+02:00) Damask',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Israel Standard Time',120,'(UTC+02:00) Иерусалим','(GMT+02:00) Jerusalem',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Egypt Standard Time',120,'(UTC+02:00) Каир','(GMT+02:00) Cairo',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Turkey Standard Time',120,'(UTC+02:00) Стамбул','(GMT+02:00) Stambul',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Libya Standard Time',120,'(UTC+02:00) Триполи','(GMT+02:00) Tripoli',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('South Africa Standard Time',120,'(UTC+02:00) Хараре, Претория','(GMT+02:00) Harare, Pretoria',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Arabic Standard Time',180,'(UTC+03:00) Багдад','(GMT+03:00) Baghdad',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Kaliningrad Standard Time',180,'(UTC+03:00) Калининград, Минск','(GMT+03:00) Kaliningrad, Minsk',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Arab Standard Time',180,'(UTC+03:00) Кувейт, Эр-Рияд','(GMT+03:00) Kuwait, Riyadh',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('E. Africa Standard Time',180,'(UTC+03:00) Найроби','(GMT+03:00) Nairobi',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Iran Standard Time',210,'(UTC+03:30) Тегеран','(GMT+03:30) Tehran',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Arabian Standard Time',240,'(UTC+04:00) Абу-Даби, Мускат','(GMT+04:00) Abu Dhabi, Muscat',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Azerbaijan Standard Time',240,'(UTC+04:00) Баку','(GMT+04:00) Baku',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Russian Standard Time',240,'(UTC+04:00) Волгоград, Москва, Санкт-Петербург','(GMT+03:00) Moscow, St. Petersburg, Volgograd',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Caucasus Standard Time',240,'(UTC+04:00) Ереван','(GMT+04:00) Yerevan',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Mauritius Standard Time',240,'(UTC+04:00) Порт-Луи','(GMT+04:00) Port Louis',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Georgian Standard Time',240,'(UTC+04:00) Тбилиси','(GMT+04:00) Tbilisi',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Afghanistan Standard Time',270,'(UTC+04:30) Кабул','(GMT+04:30) Kabul',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('West Asia Standard Time',300,'(UTC+05:00) Ашхабад, Ташкент','(GMT+05:00) Tashkent',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Pakistan Standard Time',300,'(UTC+05:00) Исламабад, Карачи','(GMT+05:00) Islamabad, Karachi',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('India Standard Time',330,'(UTC+05:30) Колката, Мумбаи, Нью-Дели, Ченнай','(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Sri Lanka Standard Time',330,'(UTC+05:30) Шри-Джаявардене-пура-Котте','(GMT+05:30) Sri Jayawardenepura',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Nepal Standard Time',345,'(UTC+05:45) Катманду','(GMT+05:45) Kathmandu',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Asia Standard Time',360,'(UTC+06:00) Астана','(GMT+06:00) Astana, Dhaka',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Bangladesh Standard Time',360,'(UTC+06:00) Дакка','(GMT+06:00) Dakka',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Ekaterinburg Standard Time',360,'(UTC+06:00) Екатеринбург','(GMT+05:00) Ekaterinburg',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Myanmar Standard Time',390,'(UTC+06:30) Янгон','(GMT+06:30) Yangon (Rangoon)',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('SE Asia Standard Time',420,'(UTC+07:00) Бангкок, Джакарта, Ханой','(GMT+07:00) Bangkok, Hanoi, Jakarta',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('N. Central Asia Standard Time',420,'(UTC+07:00) Новосибирск','(GMT+06:00) Almaty, Novosibirsk',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('China Standard Time',480,'(UTC+08:00) Гонконг, Пекин, Урумчи, Чунцин','(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('North Asia Standard Time',480,'(UTC+08:00) Красноярск','(GMT+07:00) Krasnoyarsk',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Singapore Standard Time',480,'(UTC+08:00) Куала-Лумпур, Сингапур','(GMT+08:00) Kuala Lumpur, Singapore',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('W. Australia Standard Time',480,'(UTC+08:00) Перт','(GMT+08:00) Perth',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Taipei Standard Time',480,'(UTC+08:00) Тайбэй','(GMT+08:00) Taipei',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Ulaanbaatar Standard Time',480,'(UTC+08:00) Улан-Батор','(GMT+08:00) Ulan-Bator',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('North Asia East Standard Time',540,'(UTC+09:00) Иркутск','(GMT+08:00) Irkutsk, Ulaan Bataar',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Tokyo Standard Time',540,'(UTC+09:00) Осака, Саппоро, Токио','(GMT+09:00) Osaka, Sapporo, Tokyo',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Korea Standard Time',540,'(UTC+09:00) Сеул','(GMT+09:00) Seoul',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Cen. Australia Standard Time',570,'(UTC+09:30) Аделаида','(GMT+09:30) Adelaide',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('AUS Central Standard Time',570,'(UTC+09:30) Дарвин','(GMT+09:30) Darwin',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('E. Australia Standard Time',600,'(UTC+10:00) Брисбен','(GMT+10:00) Brisbane',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('West Pacific Standard Time',600,'(UTC+10:00) Гуам, Порт-Морсби','(GMT+10:00) Guam, Port Moresby',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('AUS Eastern Standard Time',600,'(UTC+10:00) Канберра, Мельбурн, Сидней','(GMT+10:00) Canberra, Melbourne, Sydney',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Tasmania Standard Time',600,'(UTC+10:00) Хобарт','(GMT+10:00) Hobart',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Yakutsk Standard Time',600,'(UTC+10:00) Якутск','(GMT+09:00) Yakutsk',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Vladivostok Standard Time',660,'(UTC+11:00) Владивосток','(GMT+10:00) Vladivostok',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Central Pacific Standard Time',660,'(UTC+11:00) Соломоновы о-ва, Нов. Каледония','(GMT+11:00) Magadan, Solomon Is., New Caledonia',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('New Zealand Standard Time',720,'(UTC+12:00) Веллингтон, Окленд','(GMT+12:00) Auckland, Wellington',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('UTC+12',720,'(UTC+12:00) Время в формате UTC +12','(GMT+12:00) UTC time',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Magadan Standard Time',720,'(UTC+12:00) Магадан','(GMT+12:00) Magadan',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Kamchatka Standard Time',720,'(UTC+12:00) Петропавловск-Камчатский — устаревшее','(GMT+12:00) Petropavlovsk-Kamchatskiy - old',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Fiji Standard Time',720,'(UTC+12:00) Фиджи','(GMT+12:00) Fiji, Kamchatka, Marshall Is.',1)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Tonga Standard Time',780,'(UTC+13:00) Нукуалофа','(GMT+13:00) Nukualofa',0)
INSERT INTO [dbo].[TimeZones]([SystemId],[UTCOffset],[TimeZoneNameRu],[TimeZoneNameEn],[SupportSummerTime])VALUES('Samoa Standard Time',780,'(UTC+13:00) Самоа','(GMT-11:00) Midway Island, Samoa',1)
GO
--USERS   --P:doc123456
DECLARE @UserId INT 
INSERT INTO [dbo].[AspNetUsers]([Email],[EmailConfirmed],[PasswordHash],[SecurityStamp],[PhoneNumber],[PhoneNumberConfirmed],[TwoFactorEnabled],
[LockoutEndDateUtc],[LockoutEnabled],[AccessFailedCount],[UserName])VALUES('testdocru@mail.com',1,'AF3yPDAZr79gunebF5p8A4LFw399LodrXCTkybH8dfW+PwQIX6nJKFCi6OeTA+Jl4w==',
'06ee7c15-5e24-4d0e-8f52-d5913f37e6d9',NULL,0,0,NULL,0,0,'testdocru@mail.com')
set @UserId = SCOPE_IDENTITY()
INSERT INTO [dbo].[AspNetUserRoles]([UserId],[RoleId])VALUES(@UserId,2)
INSERT INTO [dbo].[UserInfo]([AspNetUserId],[TimeZoneId],[LanguageId],[CreateDateUtc],[UpdateDateUtc],[LastActivityDateUtc],[IsLocked],[IsDeleted])
     VALUES(@UserId,56,2,GETUTCDATE(),GETUTCDATE(),GETUTCDATE(),0,0)
GO

DECLARE @NewUserId INT 
INSERT INTO [dbo].[AspNetUsers]([Email],[EmailConfirmed],[PasswordHash],[SecurityStamp],[PhoneNumber],[PhoneNumberConfirmed],[TwoFactorEnabled],
[LockoutEndDateUtc],[LockoutEnabled],[AccessFailedCount],[UserName])VALUES('testdoc@mail.com',1,'AOHwXwamr2n9Ned8RJ6xluGQe4paFy6N+2VFDQr5aoQfv3U6cG877x+YFl5riyidaA==',
'bbe0b05c-4287-4927-8e01-58e9eea654f3',NULL,0,0,NULL,0,0,'testdoc@mail.com')
set @NewUserId = SCOPE_IDENTITY()
INSERT INTO [dbo].[AspNetUserRoles]([UserId],[RoleId])VALUES(@NewUserId,2)
INSERT INTO [dbo].[UserInfo]([AspNetUserId],[TimeZoneId],[LanguageId],[CreateDateUtc],[UpdateDateUtc],[LastActivityDateUtc],[IsLocked],[IsDeleted])
     VALUES(@NewUserId,56,1,GETUTCDATE(),GETUTCDATE(),GETUTCDATE(),0,0)
GO