--CREATE VIEW dbo.vPatient
--AS
--SELECT     dbo.PatientInfo.Id, dbo.PatientInfo.CardNumber, ISNULL(dbo.ContactInfo.Surname, N'') + N' ' + ISNULL(dbo.ContactInfo.Name, N'') AS FullName, 
--                      dbo.PatientInfo.Comment, dbo.PatientInfo.WorkPlace, dbo.PatientInfo.OwnerId, dbo.PatientInfo.CreateDateTime, dbo.PatientInfo.CreateUserId, 
--                      dbo.PatientInfo.UpdateDateTime, dbo.PatientInfo.UpdateUserId, dbo.ContactInfo.Name, dbo.ContactInfo.Surname, dbo.ContactInfo.MiddleName, 
--                      dbo.ContactInfo.Gender, dbo.ContactInfo.Birthday, dbo.ContactInfo.PhoneCell, dbo.ContactInfo.PhoneCellNotUse, dbo.ContactInfo.PhoneHome, 
--                      dbo.ContactInfo.PhoneHomeNotUse, dbo.ContactInfo.Fax, dbo.ContactInfo.Email, dbo.ContactInfo.EmailNotUse, ISNULL
--                          ((SELECT     COUNT(*) AS Expr1
--                              FROM         dbo.PatientVisit AS pv
--                              WHERE     (dbo.PatientInfo.Id = PatientId)), 0) AS VisitCount, ISNULL
--                          ((SELECT     SUM(CostOfServices - Paid) AS Expr1
--                              FROM         dbo.PatientVisitPayment AS pvp
--                              WHERE     (dbo.PatientInfo.Id = PatientId)), 0) AS Debt
--FROM         dbo.PatientInfo INNER JOIN
--                      dbo.ContactInfo ON dbo.PatientInfo.ContactInfoId = dbo.ContactInfo.Id

--GO
--EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
--Begin DesignProperties = 
--   Begin PaneConfigurations = 
--      Begin PaneConfiguration = 0
--         NumPanes = 4
--         Configuration = "(H (1[32] 4[29] 2[20] 3) )"
--      End
--      Begin PaneConfiguration = 1
--         NumPanes = 3
--         Configuration = "(H (1 [50] 4 [25] 3))"
--      End
--      Begin PaneConfiguration = 2
--         NumPanes = 3
--         Configuration = "(H (1 [50] 2 [25] 3))"
--      End
--      Begin PaneConfiguration = 3
--         NumPanes = 3
--         Configuration = "(H (4 [30] 2 [40] 3))"
--      End
--      Begin PaneConfiguration = 4
--         NumPanes = 2
--         Configuration = "(H (1 [56] 3))"
--      End
--      Begin PaneConfiguration = 5
--         NumPanes = 2
--         Configuration = "(H (2 [66] 3))"
--      End
--      Begin PaneConfiguration = 6
--         NumPanes = 2
--         Configuration = "(H (4 [50] 3))"
--      End
--      Begin PaneConfiguration = 7
--         NumPanes = 1
--         Configuration = "(V (3))"
--      End
--      Begin PaneConfiguration = 8
--         NumPanes = 3
--         Configuration = "(H (1[56] 4[18] 2) )"
--      End
--      Begin PaneConfiguration = 9
--         NumPanes = 2
--         Configuration = "(H (1 [75] 4))"
--      End
--      Begin PaneConfiguration = 10
--         NumPanes = 2
--         Configuration = "(H (1[66] 2) )"
--      End
--      Begin PaneConfiguration = 11
--         NumPanes = 2
--         Configuration = "(H (4 [60] 2))"
--      End
--      Begin PaneConfiguration = 12
--         NumPanes = 1
--         Configuration = "(H (1) )"
--      End
--      Begin PaneConfiguration = 13
--         NumPanes = 1
--         Configuration = "(V (4))"
--      End
--      Begin PaneConfiguration = 14
--         NumPanes = 1
--         Configuration = "(V (2))"
--      End
--      ActivePaneConfig = 0
--   End
--   Begin DiagramPane = 
--      Begin Origin = 
--         Top = 0
--         Left = 0
--      End
--      Begin Tables = 
--         Begin Table = "PatientInfo"
--            Begin Extent = 
--               Top = 6
--               Left = 38
--               Bottom = 232
--               Right = 207
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "ContactInfo"
--            Begin Extent = 
--               Top = 6
--               Left = 245
--               Bottom = 264
--               Right = 426
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--      End
--   End
--   Begin SQLPane = 
--   End
--   Begin DataPane = 
--      Begin ParameterDefaults = ""
--      End
--      Begin ColumnWidths = 10
--         Width = 284
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--      End
--   End
--   Begin CriteriaPane = 
--      Begin ColumnWidths = 11
--         Column = 8190
--         Alias = 900
--         Table = 1170
--         Output = 720
--         Append = 1400
--         NewValue = 1170
--         SortType = 1350
--         SortOrder = 1410
--         GroupBy = 1350
--         Filter = 1350
--         Or = 1350
--         Or = 1350
--         Or = 1350
--      End
--   End
--End
--', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vPatient';


--GO
--EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'VIEW', @level1name = N'vPatient';

